gems:
  - buildr = 1.4.6

repositories:
  remote:
   - http://repo.fire.dse.vic.gov.au/content/groups/fisg
   - http://www.ibiblio.org/maven2
  release_to:
    url: http://repo.fire.dse.vic.gov.au/content/repositories/releases/
    username: upload

artifacts:
  javax_inject: javax.inject:javax.inject:jar:1
  javax_transaction: javax.transaction:jta:jar:1.1
  javax_interceptor: org.apache.geronimo.specs:geronimo-interceptor_1.1_spec:jar:1.0
  javax_naming: geronimo:geronimo-naming:jar:1.1.1
  javax_persistence: org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.0.Final
  javax_annotation: com.google.code.findbugs:jsr305:jar:1.3.9
  gwt_user: com.google.gwt:gwt-user:jar:2.3.0

  # Encoding on the server
  json: org.json:json:jar:20090211

  # Testing encoding on the server
  jsonpath: com.jayway.jsonpath:json-path:jar:0.5.5
  json_smart: net.minidev:json-smart:jar:1.0.9

  #
  # Mocking library
  mockito: org.mockito:mockito-all:jar:1.8.5
