repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_inject: javax.inject:javax.inject:jar:1
  javax_transaction: javax.transaction:jta:jar:1.1
  javax_interceptor: org.apache.geronimo.specs:geronimo-interceptor_1.1_spec:jar:1.0
  javax_naming: geronimo:geronimo-naming:jar:1.1.1
  javax_persistence: org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.0.Final
  javax_annotation: com.google.code.findbugs:jsr305:jar:1.3.9
  gwt_user: com.google.gwt:gwt-user:jar:2.5.1

  # Encoding on the server
  json: org.json:json:jar:20090211

  #
  # Mocking library
  mockito: org.mockito:mockito-all:jar:1.9.5

  # JEE7 json library
  javax_json: org.glassfish:javax.json:jar:1.0.3
